packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.30.0
  '@hookform/resolvers': ^5.0.1
  '@nestjs/common': ^11.1.3
  '@nestjs/config': ^4.0.2
  '@nestjs/swagger': ^11.2.0
  '@nestjs/throttler': ^6.4.0
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  date-fns: 4.1.0
  eslint: ^9.27.0
  helmet: ^8.1.0
  pino-http: ^10.5.0
  pino-nestjs: ^0.1.3
  prettier: ^3.5.3
  react: 19.0.0
  react-dom: 19.0.0
  react-hook-form: 7.69.0
  tsup: ^8.5.0
  typescript: ^5.8.3
  zod: ^3.25.74
