/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root';
import {Route as PublicRouteRouteImport} from './routes/_public/route';
import {Route as _pathlessLayoutRouteRouteImport} from './routes/__pathlessLayout/route';
import {Route as PublicIndexRouteImport} from './routes/_public/index';
import {Route as PublicWelcomeRouteImport} from './routes/_public/welcome';
import {Route as _pathlessLayoutSettingsRouteImport} from './routes/__pathlessLayout/settings';
import {Route as PublicApartmentsRouteRouteImport} from './routes/_public/apartments/route';
import {Route as PublicApartmentsIndexRouteImport} from './routes/_public/apartments/index';
import {Route as PublicApartmentsApartmentIdRouteImport} from './routes/_public/apartments/$apartmentId';

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const _pathlessLayoutRouteRoute = _pathlessLayoutRouteRouteImport.update({
  id: '/__pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicWelcomeRoute = PublicWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => PublicRouteRoute,
} as any);
const _pathlessLayoutSettingsRoute = _pathlessLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => _pathlessLayoutRouteRoute,
} as any);
const PublicApartmentsRouteRoute = PublicApartmentsRouteRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicApartmentsIndexRoute = PublicApartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicApartmentsRouteRoute,
} as any);
const PublicApartmentsApartmentIdRoute = PublicApartmentsApartmentIdRouteImport.update({
  id: '/$apartmentId',
  path: '/$apartmentId',
  getParentRoute: () => PublicApartmentsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/apartments': typeof PublicApartmentsRouteRouteWithChildren;
  '/settings': typeof _pathlessLayoutSettingsRoute;
  '/welcome': typeof PublicWelcomeRoute;
  '/': typeof PublicIndexRoute;
  '/apartments/$apartmentId': typeof PublicApartmentsApartmentIdRoute;
  '/apartments/': typeof PublicApartmentsIndexRoute;
}
export interface FileRoutesByTo {
  '/settings': typeof _pathlessLayoutSettingsRoute;
  '/welcome': typeof PublicWelcomeRoute;
  '/': typeof PublicIndexRoute;
  '/apartments/$apartmentId': typeof PublicApartmentsApartmentIdRoute;
  '/apartments': typeof PublicApartmentsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/__pathlessLayout': typeof _pathlessLayoutRouteRouteWithChildren;
  '/_public': typeof PublicRouteRouteWithChildren;
  '/_public/apartments': typeof PublicApartmentsRouteRouteWithChildren;
  '/__pathlessLayout/settings': typeof _pathlessLayoutSettingsRoute;
  '/_public/welcome': typeof PublicWelcomeRoute;
  '/_public/': typeof PublicIndexRoute;
  '/_public/apartments/$apartmentId': typeof PublicApartmentsApartmentIdRoute;
  '/_public/apartments/': typeof PublicApartmentsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/apartments' | '/settings' | '/welcome' | '/' | '/apartments/$apartmentId' | '/apartments/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/settings' | '/welcome' | '/' | '/apartments/$apartmentId' | '/apartments';
  id:
    | '__root__'
    | '/__pathlessLayout'
    | '/_public'
    | '/_public/apartments'
    | '/__pathlessLayout/settings'
    | '/_public/welcome'
    | '/_public/'
    | '/_public/apartments/$apartmentId'
    | '/_public/apartments/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  _pathlessLayoutRouteRoute: typeof _pathlessLayoutRouteRouteWithChildren;
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/__pathlessLayout': {
      id: '/__pathlessLayout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof _pathlessLayoutRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/': {
      id: '/_public/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/welcome': {
      id: '/_public/welcome';
      path: '/welcome';
      fullPath: '/welcome';
      preLoaderRoute: typeof PublicWelcomeRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/__pathlessLayout/settings': {
      id: '/__pathlessLayout/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof _pathlessLayoutSettingsRouteImport;
      parentRoute: typeof _pathlessLayoutRouteRoute;
    };
    '/_public/apartments': {
      id: '/_public/apartments';
      path: '/apartments';
      fullPath: '/apartments';
      preLoaderRoute: typeof PublicApartmentsRouteRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/apartments/': {
      id: '/_public/apartments/';
      path: '/';
      fullPath: '/apartments/';
      preLoaderRoute: typeof PublicApartmentsIndexRouteImport;
      parentRoute: typeof PublicApartmentsRouteRoute;
    };
    '/_public/apartments/$apartmentId': {
      id: '/_public/apartments/$apartmentId';
      path: '/$apartmentId';
      fullPath: '/apartments/$apartmentId';
      preLoaderRoute: typeof PublicApartmentsApartmentIdRouteImport;
      parentRoute: typeof PublicApartmentsRouteRoute;
    };
  }
}

interface _pathlessLayoutRouteRouteChildren {
  _pathlessLayoutSettingsRoute: typeof _pathlessLayoutSettingsRoute;
}

const _pathlessLayoutRouteRouteChildren: _pathlessLayoutRouteRouteChildren = {
  _pathlessLayoutSettingsRoute: _pathlessLayoutSettingsRoute,
};

const _pathlessLayoutRouteRouteWithChildren = _pathlessLayoutRouteRoute._addFileChildren(
  _pathlessLayoutRouteRouteChildren,
);

interface PublicApartmentsRouteRouteChildren {
  PublicApartmentsApartmentIdRoute: typeof PublicApartmentsApartmentIdRoute;
  PublicApartmentsIndexRoute: typeof PublicApartmentsIndexRoute;
}

const PublicApartmentsRouteRouteChildren: PublicApartmentsRouteRouteChildren = {
  PublicApartmentsApartmentIdRoute: PublicApartmentsApartmentIdRoute,
  PublicApartmentsIndexRoute: PublicApartmentsIndexRoute,
};

const PublicApartmentsRouteRouteWithChildren = PublicApartmentsRouteRoute._addFileChildren(
  PublicApartmentsRouteRouteChildren,
);

interface PublicRouteRouteChildren {
  PublicApartmentsRouteRoute: typeof PublicApartmentsRouteRouteWithChildren;
  PublicWelcomeRoute: typeof PublicWelcomeRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicApartmentsRouteRoute: PublicApartmentsRouteRouteWithChildren,
  PublicWelcomeRoute: PublicWelcomeRoute,
  PublicIndexRoute: PublicIndexRoute,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(PublicRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  _pathlessLayoutRouteRoute: _pathlessLayoutRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
