/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {Route as rootRouteImport} from './routes/__root';
import {Route as LoginRouteImport} from './routes/login';
import {Route as InvalidRouteImport} from './routes/invalid';
import {Route as PublicRouteRouteImport} from './routes/_public/route';
import {Route as _adminRouteRouteImport} from './routes/__admin/route';
import {Route as PublicIndexRouteImport} from './routes/_public/index';
import {Route as _adminDashboardRouteImport} from './routes/__admin/dashboard';
import {Route as PublicApartmentsRouteRouteImport} from './routes/_public/apartments/route';
import {Route as PublicApartmentsIndexRouteImport} from './routes/_public/apartments/index';
import {Route as PublicApartmentsApartmentIdRouteImport} from './routes/_public/apartments/$apartmentId';

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const InvalidRoute = InvalidRouteImport.update({
  id: '/invalid',
  path: '/invalid',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any);
const _adminRouteRoute = _adminRouteRouteImport.update({
  id: '/__admin',
  getParentRoute: () => rootRouteImport,
} as any);
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any);
const _adminDashboardRoute = _adminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _adminRouteRoute,
} as any);
const PublicApartmentsRouteRoute = PublicApartmentsRouteRouteImport.update({
  id: '/apartments',
  path: '/apartments',
  getParentRoute: () => PublicRouteRoute,
} as any);
const PublicApartmentsIndexRoute = PublicApartmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicApartmentsRouteRoute,
} as any);
const PublicApartmentsApartmentIdRoute = PublicApartmentsApartmentIdRouteImport.update({
  id: '/$apartmentId',
  path: '/$apartmentId',
  getParentRoute: () => PublicApartmentsRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  '/invalid': typeof InvalidRoute;
  '/login': typeof LoginRoute;
  '/apartments': typeof PublicApartmentsRouteRouteWithChildren;
  '/dashboard': typeof _adminDashboardRoute;
  '/': typeof PublicIndexRoute;
  '/apartments/$apartmentId': typeof PublicApartmentsApartmentIdRoute;
  '/apartments/': typeof PublicApartmentsIndexRoute;
}
export interface FileRoutesByTo {
  '/invalid': typeof InvalidRoute;
  '/login': typeof LoginRoute;
  '/dashboard': typeof _adminDashboardRoute;
  '/': typeof PublicIndexRoute;
  '/apartments/$apartmentId': typeof PublicApartmentsApartmentIdRoute;
  '/apartments': typeof PublicApartmentsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/__admin': typeof _adminRouteRouteWithChildren;
  '/_public': typeof PublicRouteRouteWithChildren;
  '/invalid': typeof InvalidRoute;
  '/login': typeof LoginRoute;
  '/_public/apartments': typeof PublicApartmentsRouteRouteWithChildren;
  '/__admin/dashboard': typeof _adminDashboardRoute;
  '/_public/': typeof PublicIndexRoute;
  '/_public/apartments/$apartmentId': typeof PublicApartmentsApartmentIdRoute;
  '/_public/apartments/': typeof PublicApartmentsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/invalid' | '/login' | '/apartments' | '/dashboard' | '/' | '/apartments/$apartmentId' | '/apartments/';
  fileRoutesByTo: FileRoutesByTo;
  to: '/invalid' | '/login' | '/dashboard' | '/' | '/apartments/$apartmentId' | '/apartments';
  id:
    | '__root__'
    | '/__admin'
    | '/_public'
    | '/invalid'
    | '/login'
    | '/_public/apartments'
    | '/__admin/dashboard'
    | '/_public/'
    | '/_public/apartments/$apartmentId'
    | '/_public/apartments/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  _adminRouteRoute: typeof _adminRouteRouteWithChildren;
  PublicRouteRoute: typeof PublicRouteRouteWithChildren;
  InvalidRoute: typeof InvalidRoute;
  LoginRoute: typeof LoginRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/invalid': {
      id: '/invalid';
      path: '/invalid';
      fullPath: '/invalid';
      preLoaderRoute: typeof InvalidRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public': {
      id: '/_public';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof PublicRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/__admin': {
      id: '/__admin';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof _adminRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_public/': {
      id: '/_public/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PublicIndexRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/__admin/dashboard': {
      id: '/__admin/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof _adminDashboardRouteImport;
      parentRoute: typeof _adminRouteRoute;
    };
    '/_public/apartments': {
      id: '/_public/apartments';
      path: '/apartments';
      fullPath: '/apartments';
      preLoaderRoute: typeof PublicApartmentsRouteRouteImport;
      parentRoute: typeof PublicRouteRoute;
    };
    '/_public/apartments/': {
      id: '/_public/apartments/';
      path: '/';
      fullPath: '/apartments/';
      preLoaderRoute: typeof PublicApartmentsIndexRouteImport;
      parentRoute: typeof PublicApartmentsRouteRoute;
    };
    '/_public/apartments/$apartmentId': {
      id: '/_public/apartments/$apartmentId';
      path: '/$apartmentId';
      fullPath: '/apartments/$apartmentId';
      preLoaderRoute: typeof PublicApartmentsApartmentIdRouteImport;
      parentRoute: typeof PublicApartmentsRouteRoute;
    };
  }
}

interface _adminRouteRouteChildren {
  _adminDashboardRoute: typeof _adminDashboardRoute;
}

const _adminRouteRouteChildren: _adminRouteRouteChildren = {
  _adminDashboardRoute: _adminDashboardRoute,
};

const _adminRouteRouteWithChildren = _adminRouteRoute._addFileChildren(_adminRouteRouteChildren);

interface PublicApartmentsRouteRouteChildren {
  PublicApartmentsApartmentIdRoute: typeof PublicApartmentsApartmentIdRoute;
  PublicApartmentsIndexRoute: typeof PublicApartmentsIndexRoute;
}

const PublicApartmentsRouteRouteChildren: PublicApartmentsRouteRouteChildren = {
  PublicApartmentsApartmentIdRoute: PublicApartmentsApartmentIdRoute,
  PublicApartmentsIndexRoute: PublicApartmentsIndexRoute,
};

const PublicApartmentsRouteRouteWithChildren = PublicApartmentsRouteRoute._addFileChildren(
  PublicApartmentsRouteRouteChildren,
);

interface PublicRouteRouteChildren {
  PublicApartmentsRouteRoute: typeof PublicApartmentsRouteRouteWithChildren;
  PublicIndexRoute: typeof PublicIndexRoute;
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicApartmentsRouteRoute: PublicApartmentsRouteRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
};

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(PublicRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  _adminRouteRoute: _adminRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  InvalidRoute: InvalidRoute,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();
